### PR TITLE
Samsung 'CAD' file support

### PR DESCRIPTION
**Pull request by skvatboy**
Not finished it's a start.
skaermbillede_2018-07-20_15-40-56

### CODE REVIEW

**Comment by piernov** [comment]
Thanks! I guess this is related to #135?

If possible, add a `verifyFormat()` method to check for magic number/strings in the file for file format recognition, as the `cad` extension is probably used by various formats.

**Comment by inflex** [comment]
Bit hard to decide what to put in for the format testing. There's no real single key ID tag, but some of the attributes are moderately unique, such as the presence of;
```
P_ADDP 
```
or 

```
###Panel Added Part Information
```

Not sure how consistently their existence is.  Perhaps combine with the .cad extension ?

**Comment by inflex** [comment]
Is this still very much a work in progress @skvatboy ?   I noticed that the nets are mostly all the same.

Part outlines, placements and pins seem fine though.

Also, for the verifyFormat() call, try the following;

```
	static bool verifyFormat(std::vector<char> &buf);
```
and

```
bool CADFile::verifyFormat(std::vector<char> &buf) {
	return (find_str_in_buf("P_ADDP", buf) && find_str_in_buf("C_PIN", buf));
}
![s](https://user-images.githubusercontent.com/5660591/43044466-bddc7f20-8de9-11e8-88ab-1b9f34cf99c5.png)

```

**Comment by skvatboy** [comment]
Thank for the feedback.
Add verifyFormat() call and fix the nets

Does any of you have more .cad broad file to test this ?

**Comment by inflex** [comment]
I don't have any other CAD files, but one thing that's interesting to note is the prolific number of slash-prefixed nets there are. Not sure if it's a board specific or file format specific attribute.

I suppose that's here having a few more CAD files would be useful.

s

**Comment by inflex** [comment]
@skvatboy do you have the schematic for this board?  Would be nice to check to see how they're representing the net names with the /-prefix on the schem so we can make a decision on the best way to handle that in the BV.

**Comment by skvatboy** [comment]
No I don't. Have been looking for more examples, but no luck. I'll have been playing with the via's.

**Comment by anshadedavana** [comment]
Hi

If you guys need any other Samsung CAD file for testing purpose, please let me know and i will be glad to send it to any mail address you may refer.

**Comment by skvatboy** [comment]
Hi
@anshadedavana 
It will be great
Send me mail at skvatboy@gmail.com

**Comment by inflex** [comment]
What's our status here now @skvatboy ?  Do you feel it's ready?  

Should we redo this as a consolidated commit @piernov  ?

**Comment by piernov** [comment]
@inflex when merging you can select the "Squash and merge" option in the drop-down menu to combine the commits.

**Comment by skvatboy** [comment]
Almost done
The VIA is not show up in the viewer.
skaermbillede_2018-08-05_13-41-35

**Comment by skvatboy** [comment]
i'm done, have tested it with the files provided by anshadedavana.
and it works like a charm.

**Comment by inflex** [comment]
@skvatboy ,  can you redo the PR to suit the new changes after the #115 modification, and then I'll get this PR merged.

Sorry about the delay and (now) extra work.  Appreciated.

**Pull request merged**
