### PR TITLE
Build.sh: Cleanups

### PR DESCRIPTION
**Pull request by srakitnican**
I have found the script very difficult to follow with all text formating code that was around, there is still some text formatting code, but much smaller and IMO much better. Also moved help text from main code to a function in the beginning of the script.

### CODE REVIEW

**Comment by MattSturgeon** [comment]
Looks nice. Haven't tested it out, but I agree the script could do with some clean up.

I think `fmtText` could possibly be better named. `"$(color 2 Compiling)"` might read slightly better, for example.

**Comment by srakitnican** [comment]
I've put format originally because we are also changing font weight and whatever else could happen in that function in the future. But I don't have a strong opinion on that as long as the code is readable.

**Comment by MattSturgeon** [comment]
I like `fmt` and `color`. Either of those is fine, but `fmt` might need a comment explaining what it is/how it works since it is kinda ambiguous.

**Comment by MattSturgeon** [comment]
Merged as 2f7c67182251a57f0145100e944930e0921d10ca and a97bb92cab93a69c8acc7f433f8444ef01d91af6

**Pull request closed without merging**
