### PR TITLE
Cmake port

### PR DESCRIPTION
**Pull request by MattSturgeon**
Note: This branch includes a squashed version of @pafmaf's PR #14. I could rebase this without if I you really want, but I can't see why we shouldn't merge #14.

I've also taken a lot of inspiration from @piernov's unix port, and I'm hoping to work on integrating that next.

------------------------------

# This transitions from using a Visual Studio project, to using the CMake meta-build system.

This poses a number of advantages.

 - The project meta-data is easier to reason about in simple CMakeLists text files
 - CMake comes with a handy packaging feature. There is now a "PACKAGE" target/project that can be built to generate a Null Soft Installer setup program. (See screenshot and attached installer).
 - Fully compatible with multiple build systems. You can easily generate a Visual Studio build system just by running `cd build` `cmake ..`
 - CMake can even build using `msbuild`, allowing you to use simple commands like `cmake --build . --target package` to build the installer without even opening an IDE.

 - CMake allows us to step towards cross platform support, as it is a cross platform build system.

**I have updated the README to include CMake build instructions** and hints on the different generated build targets.

---------------------------------------------------

Screenshot

Note: to build the installer you will need [NSIS](http://nsis.sourceforge.net/Download) installed and in your `%PATH%`

-------------------------------------------------

Here is the installer built: [OpenBoardView-0.3.0-win32.exe.zip](https://github.com/chloridite/OpenBoardView/files/343069/OpenBoardView-0.3.0-win32.exe.zip)

### CODE REVIEW

**Comment by chloridite** [comment]
Looks good.

I've added you as a collaborator to the repo, with the intention of transferring ownership of the repo to the OpenBoardView org once you've added me as an admin to that org.

Apologies for being so quiet, I've been focusing 100% on my day-job.

**Comment by chloridite** [comment]
The transfer is complete.  I renamed the existing OpenBoardView repo in the org to OpenBoardView-fork.

**Comment by MattSturgeon** [comment]
Ok, cheers.

I'm closing this PR for now as @piernov has suggested a number of improvements.

I'll remove the fork repo and then merge in the [octopus merge], assuming you have no objection to the included commits (pafmaf's refrac (#14), adding "contributors" to copyright, a small goto replacement and piernov's platform files in readiness for cross-platform)

**Comment by MattSturgeon** [comment]
> Apologies for being so quiet, I've been focusing 100% on my day-job.

No, worries. Glad everything's ok.

**Comment by chloridite** [comment]
Yes, that merge looks fine by me.

**Comment by inflex** [comment]
Welcome back @chloridite .  Looks like we've got a pile of fun for you ahead.

**Comment by MattSturgeon** [comment]
> Looks like we've got a pile of fun for you ahead.

Lol, the @OpenBoardView/maintainers team can do the bulk of the work ;-)

**Pull request closed without merging**
